### ISSUE TITLE
Updating website

### ISSUE THREAD

**Issue by wbnns** [congoclub/cdc_site#1]
Hello, I would like to help update the website, if welcome. Here are a few ideas that I had:

1. Remove the countdown text at the top of the page
2. Update the `We are currently working hard on our new awesome website` text to something that encourages people to join the communities (e.g. Slack, Telegram)
3. Update the WhatsApp link (it is expired)
4. Fix the social media links at the bottom of the page to point to the correct places
5. Maybe update some of the pictures that display in the background (a couple of them make the text a little hard to read)

Please let me know if it would OK to proceed with working on these changes and I will open a pull request.

**Comment by davidkathoh** [comment]
Hello @wbnns, I like these ideas and your update to the website is really welcome.
Here are our social media links:
Twitter =>  https://twitter.com/CongoClub   
Linkedin => https://www.linkedin.com/company/congo-developers-club

**Comment by guillainbisimwa** [comment]
Hello @wbnns, you are welcome! Feel free to create any pull request.

**Comment by wbnns** [comment]
@davidkathoh @guillainbisimwa 

Ok great, thanks guys! Will get to work on this. 👍
