### ISSUE TITLE
Register domain for CDC website?

### ISSUE THREAD

**Issue by wbnns** [congoclub/cdc_site#4]
I saw that both `congodevelopersclub.com` and `congodevelopersclub.org` are both available. If welcome, I would be happy to register one of those and point the website in this repository at it. Just let me know if so.

**Comment by wbnns** [comment]
An additional note that `congodevelopers.com` and `congodevelopers.org` is also available.

**Comment by davidkathoh** [comment]
Awesome, would help register [congodevelopers.com](congodevelopers.com). Thank you

**Comment by wbnns** [comment]
Cool, done! You just need to go here and add it as the custom domain:

![image](https://user-images.githubusercontent.com/1130872/107159560-2eb94400-6991-11eb-80c7-89df6ad32892.png)

Reference: https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

Once you've done that, I can finish the rest. 👍

**Comment by wbnns** [comment]
@davidkathoh 

Please also select the `Enforce HTTPS` option when you add the custom domain name.

![image](https://user-images.githubusercontent.com/1130872/107159939-7e990a80-6993-11eb-888e-bcb853a3a491.png)

**Comment by davidkathoh** [comment]
Done, but for **Enforce HTTPS** we will need to wait I think.
![httpCdc](https://user-images.githubusercontent.com/18406487/107160131-046d8380-699d-11eb-9845-fe711c0bbd49.png)

**Comment by davidkathoh** [comment]
Https is enabled now
