### ISSUE TITLE
Which logo to use?

### ISSUE THREAD

**Issue by wbnns** [congoclub/cdc_site#5]
I saw two logos, is there a preference for using one or the other on the website?

1:
![image](https://user-images.githubusercontent.com/1130872/107147679-9c448080-694f-11eb-9c89-510152a9da44.png)

2:
![image](https://user-images.githubusercontent.com/1130872/107147695-b2ead780-694f-11eb-9b6e-34b40a2b2396.png)

**Comment by davidkathoh** [comment]
The first one is fine
